version: '3'

services:
      
  career-mgr:
    build: .
    ports:
      - "3010:3010"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env

  database:
    image: postgres
    env_file:
      - .env.database
    volumes:
      - db-data:/var/lib/postgresql/data
      
  chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    ports:
      - "5900:5900"

volumes:
  db-data:
